name: Money2XP
main: tzer0.Money2XP.Money2XP
version: 0.2
author: TZer0
commands:
    m2xset:
        description: Administrates money/xp-settings.
        usage: /m2xset
    m2x:
        description: Allows players to purchase xp for iConomy-money
        usage: /m2x
    m2xtrain:
        description: Toggles trainer-setups
        usage: /m2xtrain
        